[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["corepack prepare pnpm@latest --activate","pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node packages/polyglot-point/dist/server.cjs"
