[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["npm install -g pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node packages/polyglot-point/dist/server.cjs"
