[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node dist/index.cjs"